#!/bin/sh

#this is the init script that runs inside the vm (for 32 bit rootfs only)

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export HOME=/root
export TERM=linux

mount -a

ifconfig lo 127.0.0.1

cd $HOME

while /bin/true; do
  clear
  echo "Welcome to LinuxPDF"
  echo
  echo "This is a riscv32 emulator based on"
  echo "TinyEMU, modified to run inside a PDF."
  echo
  echo "Source code:"
  echo "https://github.com/ading2210/linuxpdf"
  echo
  echo "Vladislav Rimsha CV"
  echo "https://github.com/jellyninjadev/cv.pdf/releases/download/v1.0.0/cv.pdf"
  echo
  echo "Thanks Fabrice Bellard for writing TinyEmu"
  echo "and Allen for thinking outside of the box"
  echo
  setsid sh;

done
