#!/bin/sh

#this is the init script that runs inside the vm (for 32 bit rootfs only)

export PATH=/bin:/sbin:/usr/bin:/usr/sbin:/usr/local/bin
export HOME=/root
export TERM=linux

mount -a

ifconfig lo 127.0.0.1

cd $HOME

while /bin/true; do
  clear
  echo "Welcome to LinuxPDF"
  echo "This is a riscv32 emulator running:"
  uname -sr
  echo
  echo "Source code:"
  echo "https://github.com/ading2210/linuxpdf"
  echo
  setsid sh;

done
